### ISSUE TITLE
LockFeature Tests are issued even though the Lock attribute is not in FeatureTypeList

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wfs11#18]
https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=940

**Comment by dstenger** [comment]
@bermud, do you think implementation work is necessary here?

**Comment by dstenger** [comment]
Suggestion for implementation:
 * For each feature in locking tests it is checked whether Elements <Operations> and/or <Operations><Lock></Operations> exist.
  * None or both of those elements exists: feature can be used for locking test.
  * Only the first but not the second element exists: feature must NOT be used for locking test.

Implementation has some complexity as each locking test has to be adjusted individually. In addition, the case can occur that a locking test is not executable any more due to the limitation of non-locking features. Those tests have to be skipped retrospectively.

Furthermore, is there any test service available?

Another question is if a fix in the ETS is reasonable. As this test suite is data dependent and uses test data, why should single features be excluded from locking (as locking is implemented by the server). The documentation of the ETS could be extended stating if locking is supported by the server, following list of features has to be lockable.

**Comment by dstenger** [comment]
Enhancement and pull request (#50) was created enabling separation of locking from transaction CC.

The enhancement makes possible improved error analysis regarding this issue.

**Comment by dstenger** [comment]
Pull request #50 was merged into master branch and will be part of the upcoming release.

**Comment by dstenger** [comment]
Documentation was enhanced to describe current behaviour and provided via pull request: #70
